import type { NextPage } from 'next';
import Navbar from '../../components/Navbar';
import styles from './index.module.scss';
import Head from 'next/head';
import { Table, Form, Select, Input, Button, Space } from 'antd';
const { Option } = Select;
import dummy from '../../dummy/templat.json';

import { EditFilled, DeleteFilled } from '@ant-design/icons';

const Templat: NextPage = () => {
  const columns = [
    {
      title: 'No',
      key: 'no',
      dataIndex: 'id',
    },
    { title: 'R/P', key: 'jenis', dataIndex: 'jenis' },
    { title: 'Judul', key: 'judul', dataIndex: 'judul' },
    { title: 'Deskripsi', key: 'deskripsi', dataIndex: 'deskripsi' },
    { title: 'Renstra', key: 'renstra', dataIndex: 'renstra' },
    { title: 'Kokin', key: 'kokin', dataIndex: 'kokin' },
    {
      title: 'Status',
      key: 'status',
      dataIndex: 'status',

      render: (_: null, obj: any) => ({
        props: {
          style: {
            background: obj.status ? '#52c41a' : 'inherit',
          },
        },
        children: obj.status ? 'Enable' : 'Disabled',
      }),
    },
    {
      title: '',
      key: 'action',
      dataIndex: 'status',
      width: 100,
      render: (_: null, obj: any) => (
        <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
          <Button title="Edit">
            <EditFilled />
          </Button>
          <Button title="Delete">
            <DeleteFilled />
          </Button>
        </div>
      ),
    },
  ];

  const dataTable: Array<any> = dummy;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar state="template" />

      <main className={styles.main}>
        <h1>Daftar Templat Pekerjaan</h1>

        <Form
          name="basic"
          layout="vertical"
          style={{
            width: '100%',
            display: 'flex',
            gap: 20,
            paddingLeft: 20,
            paddingRight: 20,
            paddingTop: 10,
            backgroundColor: '#ddd',
          }}
        >
          <Form.Item label="Baris" name="baris" style={{ width: 100 }}>
            <Select>
              <Option>20</Option>
              <Option>50</Option>
              <Option>100</Option>
              <Option>Semua</Option>
            </Select>
          </Form.Item>
          <Form.Item name="note" label="RENSTRA" style={{ width: 200 }}>
            <Select placeholder="Pilih RENSTRA" allowClear />
          </Form.Item>
          <Form.Item name="note" label="Kontrak Kinerja" style={{ width: 200 }}>
            <Select placeholder="Pilih KOKIN" allowClear />
          </Form.Item>
          <Form.Item name="note" label="Kata Kunci" style={{ flex: 1 }}>
            <Input />
          </Form.Item>
          <Form.Item name="note" label="R/P">
            <Select placeholder="Semua" allowClear>
              <Option>R</Option>
              <Option>P</Option>
            </Select>
          </Form.Item>
          <Form.Item name="note" label="Status">
            <Select placeholder="Semua" allowClear>
              <Option>Enabled</Option>
              <Option>Disabled</Option>
            </Select>
          </Form.Item>
          <Form.Item name="note" label="Catatan">
            <Select placeholder="Semua" allowClear>
              <Option>Ada</Option>
              <Option>Tidak Ada</Option>
            </Select>
          </Form.Item>
          <Form.Item
            style={{
              alignItems: 'flex-end',
              flexDirection: 'row',
            }}
          >
            <Button type="primary" htmlType="submit">
              Saring
            </Button>
          </Form.Item>
        </Form>

        <Table
          columns={columns}
          dataSource={dataTable}
          pagination={false}
          style={{ width: '100%', marginTop: 10 }}
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Templat;
