import React from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../../components/Navbar';

const Rka: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <h1>Halooo</h1>
      </main>

      <footer></footer>
    </div>
  );
};

export default Rka;
