import type { NextPage } from 'next';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import styles from '../styles/Home.module.css';
import { Table } from 'antd';
import dummy from '../dummy/rka.json';
import { LockOutlined, UnlockOutlined } from '@ant-design/icons';
import Link from 'next/link';

const Home: NextPage = () => {
  const formatNumber = (num: number, div = '.') => {
    return num.toString().replace(/\B(?=(\d{3})+(?!\d))/g, div);
  };
  const columns = [
    {
      title: 'RKA',
      dataIndex: 'name',
      key: 'name',
      render: (_: null, obj: any) => (
        <Link href={'/rka/' + obj.id}>{obj.name}</Link>
      ),
    },
    {
      title: '#Satker',
      dataIndex: 'satker',
      key: 'satker',
      align: 'center' as 'center',
    },
    {
      title: 'APBN',
      dataIndex: 'apbn',
      key: 'apbn',
      align: 'right' as 'right',
      render: (_: null, obj: any) => formatNumber(obj.apbn),
    },
    {
      title: 'NON-PNBP',
      dataIndex: 'non_pnbp',
      key: 'non_pnbp',
      align: 'right' as 'right',
      render: (_: null, obj: any) => formatNumber(obj.non_pnbp),
    },
    {
      title: 'BPPTN-BH',
      dataIndex: 'bpptn_bh',
      key: 'bpptn_bh',
      align: 'right' as 'right',
      render: (_: null, obj: any) => formatNumber(obj.bpptn_bh),
    },
    {
      title: 'BOPTN',
      dataIndex: 'boptn',
      key: 'boptn',
      align: 'right' as 'right',
      render: (_: null, obj: any) => formatNumber(obj.boptn),
    },
    {
      title: 'Total',
      key: 'total',
      align: 'right' as 'right',
      render: (_: null, obj: any) =>
        formatNumber(obj.apbn + obj.non_pnbp + obj.bpptn_bh + obj.boptn),
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      align: 'center' as 'center',
      render: (_: null, obj: any) => {
        return {
          props: {
            style: {
              background: obj.status == 'OPEN' ? '#52c41a' : 'inherit',
            },
          },
          children:
            obj.status == 'OPEN' ? <UnlockOutlined /> : <LockOutlined />,
        };
      },
    },
  ];
  const data = dummy;
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        <Table
          columns={columns}
          dataSource={data}
          pagination={false}
          style={{ width: '100%' }}
        />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
